spring.application.name=pricing-engine

# SQLite configuration
spring.datasource.url=jdbc:sqlite:pricing_data.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate DDL-auto options: create, create-drop, update, validate, none
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always

# Enable initialization for non-embedded databases
spring.sql.init.mode=always

# (Optional) If using Hibernate, defer data.sql until after Hibernate creates tables
spring.jpa.defer-datasource-initialization=true

# Kafka configuration
# application.properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=pricing-group
spring.kafka.consumer.auto-offset-reset=earliest

# Serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# Corrected JSON Properties (Must use spring.kafka.consumer.properties prefix)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.price.pricing_engine.model.PricingContext

# Custom Topic
pricing.kafka.topic=price-requests

# These MUST have the .properties. prefix to be passed to the Serializer/Deserializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

logging.level.org.springframework.boot.autoconfigure=DEBUG


