spring.application.name=pricing-engine

# SQLite configuration
spring.datasource.url=jdbc:sqlite:pricing_data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect
# Hibernate DDL-auto options: create, create-drop, update, validate, none
spring.jpa.hibernate.ddl-auto=update 
spring.datasource.initialization-mode=always
